/**
 * YOUTUBE TRANSCRIPT ADAPTER
 *
 * Fetches a YouTube video's transcript for free, with no third-party
 * transcript service. Each supported site gets its own adapter file like
 * this one, and every adapter returns the same shape — so the rest of the
 * extension (analysis, translation, notes, chat) never needs to know which
 * site a video came from. Adding a new site later (e.g. Bilibili) means
 * adding a new file here, not touching this one.
 *
 * HOW IT WORKS
 *
 * The first version of this file read the video player's caption track
 * list (getPlayerResponse().captions...) and fetched a track's baseUrl
 * directly. That broke: YouTube's timedtext endpoint now silently returns
 * 200 with an empty body for that kind of request, even issued from the
 * page's own origin with cookies attached — it wants some additional
 * per-request proof of origin the static baseUrl doesn't carry, and that
 * proof is generated by YouTube's own player code, not something we can
 * easily reproduce (and it would keep changing if we tried).
 *
 * So instead, this reads the transcript the same way a person would: it
 * clicks the page's own "Show transcript" button (matched structurally,
 * not by its — localized — label text) and reads back the lines YouTube's
 * own code renders into the transcript panel. That panel's own network
 * request is made and authorized by the real page, so it isn't subject to
 * the block above. All of this runs in the page's JS world (world: "MAIN"
 * via chrome.scripting.executeScript), not the extension's background,
 * since a content script can't see the page's DOM query results this way
 * either — MAIN world is what lets us reach in.
 *
 * One real trade-off from reading the rendered panel instead of the raw
 * caption file: YouTube's transcript panel doesn't expose word-level
 * timing or an explicit per-line duration, only one timestamp per line.
 * buildTranscript() below approximates both; see its comment.
 *
 * Returned shape (kept identical to the old Supadata-based fetch so every
 * caller — analysis, notes, translation, side panel rendering — needed no
 * changes):
 *   {
 *     success: true,
 *     transcript: [{ text, start (seconds), duration (seconds), language }],
 *     transcriptText: "plain text ...",
 *     transcriptTextTimestamped: "[MM:SS] line\n[MM:SS] line...",
 *     language: "en" | null,
 *   }
 *   { success: false, error: "NO_TRANSCRIPT" | ..., message: "..." }
 */
var DW_TRANSCRIPT_YOUTUBE = (() => {
  /**
   * Opens (if needed) and reads YouTube's own transcript panel, entirely
   * inside the page's own JS world.
   *
   * @returns {{ok: true, lines: [{text, start}]} | {ok: false, error}}
   */
  async function fetchInPage(tabId) {
    const results = await chrome.scripting.executeScript({
      target: { tabId },
      world: "MAIN",
      func: async () => {
        // YouTube has shipped at least two different transcript panel
        // implementations (transcript-segment-view-model is the current
        // one; ytd-transcript-segment-renderer is the older one some
        // accounts/videos may still get) — read whichever is present.
        function readSegments() {
          const nodes = document.querySelectorAll(
            "transcript-segment-view-model, ytd-transcript-segment-renderer",
          );
          const lines = [];
          for (const node of nodes) {
            // The timestamp is marked aria-hidden (a sibling carries the
            // spoken-out "1 second" label instead) and the caption text
            // carries role="text" — both are accessibility semantics, so
            // they're less likely to change than a CSS class name.
            const timestampText = (
              node.querySelector('[aria-hidden="true"]') ||
              node.querySelector(".segment-timestamp")
            )?.textContent?.trim();
            const text = (
              node.querySelector('[role="text"]') ||
              node.querySelector(".segment-text")
            )?.textContent?.trim();
            if (!timestampText || !text) continue;

            const parts = timestampText.split(":").map(Number);
            if (parts.length === 0 || parts.some((n) => Number.isNaN(n))) {
              continue;
            }
            const start = parts.reduce((total, part) => total * 60 + part, 0);
            lines.push({ text, start });
          }
          return lines;
        }

        try {
          let lines = readSegments();
          let weOpenedPanel = false;

          if (lines.length === 0) {
            // Match the button structurally (inside this custom element),
            // not by its label text, since that text is localized.
            const openButton = document.querySelector(
              "ytd-video-description-transcript-section-renderer button",
            );
            if (!openButton) {
              return { ok: false, error: "NO_TRANSCRIPT" };
            }
            openButton.click();
            weOpenedPanel = true;

            // YouTube fetches the transcript asynchronously once the panel
            // opens; poll briefly rather than fixing a single delay.
            const deadline = Date.now() + 8000;
            while (Date.now() < deadline) {
              await new Promise((resolve) => setTimeout(resolve, 200));
              lines = readSegments();
              if (lines.length > 0) break;
            }
          }

          // Best-effort: close the panel again if we're the ones who
          // opened it, so the viewer's page looks the way it did before.
          // Never treat a failure to close as an error.
          if (weOpenedPanel) {
            try {
              const panels = document.querySelectorAll(
                "ytd-engagement-panel-section-list-renderer",
              );
              for (const panel of panels) {
                if (
                  panel.getAttribute("visibility") ===
                  "ENGAGEMENT_PANEL_VISIBILITY_EXPANDED"
                ) {
                  panel.querySelector('button[aria-label="Close"]')?.click();
                }
              }
            } catch (e) {
              // Ignore — see comment above.
            }
          }

          if (lines.length === 0) {
            return { ok: false, error: "EMPTY_TRANSCRIPT" };
          }
          return { ok: true, lines };
        } catch (e) {
          return { ok: false, error: e.message || "UNKNOWN_ERROR" };
        }
      },
    });
    return (
      results?.[0]?.result || { ok: false, error: "SCRIPT_INJECTION_FAILED" }
    );
  }

  /**
   * Converts the scraped {text, start} lines into our internal transcript
   * shape.
   *
   * YouTube's transcript panel exposes one timestamp per line and no
   * word-level offsets, unlike the raw caption file this used to parse.
   * Two fields are therefore approximated rather than exact:
   *   - `duration`: the gap to the next line (0 for the last line).
   *   - `segs`: a single entry covering the whole line. Every caller that
   *     reads `segs` (the Chat tab's word-clickable subtitle view) already
   *     falls back to line-level granularity when it has just one entry,
   *     so this only means clicking a line instead of a single word.
   */
  function buildTranscript(lines) {
    const transcript = [];
    let transcriptTextPlain = "";
    let transcriptTextTimestamped = "";

    for (let i = 0; i < lines.length; i++) {
      const { text, start } = lines[i];
      if (!text) continue;

      const next = lines[i + 1];
      const duration = next ? Math.max(0, next.start - start) : 0;
      const minutes = Math.floor(start / 60);
      const seconds = start % 60;
      const timestamp = `${minutes}:${String(seconds).padStart(2, "0")}`;

      transcript.push({
        text,
        start,
        duration,
        language: null,
        segs: [{ text, offsetMs: 0 }],
      });

      transcriptTextPlain += text + " ";
      transcriptTextTimestamped += `[${timestamp}] ${text}\n`;
    }

    return {
      transcript,
      transcriptTextPlain: transcriptTextPlain.trim(),
      transcriptTextTimestamped: transcriptTextTimestamped.trim(),
    };
  }

  /**
   * Fetches the transcript for the YouTube video open in `tabId`.
   *
   * @param {number} tabId - The YouTube tab to read the player from.
   * @returns {Object} success/failure result, see file header for shape.
   */
  async function fetchTranscript(tabId) {
    if (!tabId) {
      return {
        success: false,
        error: "NO_TAB",
        message: "Could not find the YouTube tab to read captions from.",
      };
    }

    let result;
    try {
      result = await fetchInPage(tabId);
    } catch (error) {
      return {
        success: false,
        error: "PLAYER_UNAVAILABLE",
        message:
          "Could not read the video page. Reload the YouTube tab and try again.",
      };
    }

    if (!result.ok) {
      if (result.error === "NO_TRANSCRIPT") {
        return {
          success: false,
          error: "NO_TRANSCRIPT",
          message: "No transcript is available for this video.",
        };
      }
      if (result.error === "EMPTY_TRANSCRIPT") {
        return {
          success: false,
          error: "EMPTY_TRANSCRIPT",
          message:
            "YouTube's transcript panel returned no lines for this video.",
        };
      }
      return {
        success: false,
        error: "FETCH_FAILED",
        message: `Failed to read the transcript panel (${result.error}).`,
      };
    }

    const { transcript, transcriptTextPlain, transcriptTextTimestamped } =
      buildTranscript(result.lines);

    if (transcript.length === 0) {
      return {
        success: false,
        error: "EMPTY_TRANSCRIPT",
        message:
          "YouTube's transcript panel returned no lines for this video.",
      };
    }

    return {
      success: true,
      transcript,
      transcriptText: transcriptTextPlain,
      transcriptTextTimestamped: transcriptTextTimestamped,
      language: null,
    };
  }

  return { fetchTranscript, fetchInPage, buildTranscript };
})();

if (typeof module !== "undefined" && module.exports) {
  module.exports = DW_TRANSCRIPT_YOUTUBE;
}
