/**
 * YOUTUBE TRANSCRIPT ADAPTER
 *
 * Fetches a YouTube video's transcript for free, with no third-party
 * transcript service. Each supported site gets its own adapter file like
 * this one, and every adapter returns the same shape — so the rest of the
 * extension (analysis, translation, notes, chat) never needs to know which
 * site a video came from. Adding a new site later (e.g. Bilibili) means
 * adding a new file here, not touching this one.
 *
 * HOW IT WORKS
 *
 * The first version of this file read the video player's caption track
 * list (getPlayerResponse().captions...) and fetched a track's baseUrl
 * directly. That broke: YouTube's timedtext endpoint now silently returns
 * 200 with an empty body for that kind of request, even issued from the
 * page's own origin with cookies attached — it wants some additional
 * per-request proof of origin the static baseUrl doesn't carry, and that
 * proof is generated by YouTube's own player code, not something we can
 * easily reproduce (and it would keep changing if we tried).
 *
 * So instead, this reads the transcript the same way a person would: it
 * clicks the page's own "Show transcript" button (matched structurally,
 * not by its — localized — label text) and reads back the lines YouTube's
 * own code renders into the transcript panel. That panel's own network
 * request is made and authorized by the real page, so it isn't subject to
 * the block above. All of this runs in the page's JS world (world: "MAIN"
 * via chrome.scripting.executeScript), not the extension's background,
 * since a content script can't see the page's DOM query results this way
 * either — MAIN world is what lets us reach in.
 *
 * One real trade-off from reading the rendered panel instead of the raw
 * caption file: YouTube's transcript panel doesn't expose word-level
 * timing or an explicit per-line duration, only one timestamp per line.
 * buildTranscript() below approximates both; see its comment.
 *
 * Returned shape (kept identical to the old Supadata-based fetch so every
 * caller — analysis, notes, translation, side panel rendering — needed no
 * changes):
 *   {
 *     success: true,
 *     transcript: [{ text, start (seconds), duration (seconds), language }],
 *     transcriptText: "plain text ...",
 *     transcriptTextTimestamped: "[MM:SS] line\n[MM:SS] line...",
 *     language: "en" | null,
 *   }
 *   { success: false, error: "NO_TRANSCRIPT" | ..., message: "..." }
 */
var DW_TRANSCRIPT_YOUTUBE = (() => {
  /**
   * Opens (if needed) and reads YouTube's own transcript panel, entirely
   * inside the page's own JS world.
   *
   * YouTube is a single-page app: the transcript panel's DOM survives
   * navigation, so after watching video A its lines are still sitting in the
   * (closed) panel when video B loads. Reading "whatever lines are there"
   * therefore returns A's transcript for B. To prevent that, every
   * successful read is stamped on the page (window.__deepWatchTranscript) with
   * the video it came from and a signature of its lines; existing lines are
   * only trusted when that stamp matches the requested video, otherwise the
   * panel is reopened and we wait for YouTube to replace them.
   *
   * @param {number} tabId
   * @param {string|null} expectedVideoId - The video the caller wants; the
   *   page is checked to actually be showing it.
   * @returns {{ok: true, lines: [{text, start}]} | {ok: false, error}}
   */
  async function fetchInPage(tabId, expectedVideoId) {
    const results = await chrome.scripting.executeScript({
      target: { tabId },
      world: "MAIN",
      args: [expectedVideoId || null],
      func: async (videoId) => {
        // YouTube has shipped at least two different transcript panel
        // implementations (transcript-segment-view-model is the current
        // one; ytd-transcript-segment-renderer is the older one some
        // accounts/videos may still get) — read whichever is present.
        function readSegments() {
          const nodes = document.querySelectorAll(
            "transcript-segment-view-model, ytd-transcript-segment-renderer",
          );
          const lines = [];
          for (const node of nodes) {
            // The timestamp is marked aria-hidden (a sibling carries the
            // spoken-out "1 second" label instead) and the caption text
            // carries role="text" — both are accessibility semantics, so
            // they're less likely to change than a CSS class name.
            const timestampText = (
              node.querySelector('[aria-hidden="true"]') ||
              node.querySelector(".segment-timestamp")
            )?.textContent?.trim();
            const text = (
              node.querySelector('[role="text"]') ||
              node.querySelector(".segment-text")
            )?.textContent?.trim();
            if (!timestampText || !text) continue;

            const parts = timestampText.split(":").map(Number);
            if (parts.length === 0 || parts.some((n) => Number.isNaN(n))) {
              continue;
            }
            const start = parts.reduce((total, part) => total * 60 + part, 0);
            lines.push({ text, start });
          }
          return lines;
        }

        const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

        // A cheap fingerprint of a set of lines, used to tell "the panel
        // still holds the previous content" from "the panel was refreshed".
        function signature(lines) {
          if (lines.length === 0) return null;
          const last = lines[lines.length - 1];
          return `${lines.length}|${lines[0].text}|${last.start}|${last.text}`;
        }

        function transcriptPanelIsOpen() {
          return Array.from(
            document.querySelectorAll(
              "ytd-engagement-panel-section-list-renderer",
            ),
          ).some(
            (panel) =>
              panel.getAttribute("visibility") ===
                "ENGAGEMENT_PANEL_VISIBILITY_EXPANDED" &&
              panel.querySelector(
                "transcript-segment-view-model, ytd-transcript-segment-renderer",
              ),
          );
        }

        function closeOpenPanels() {
          try {
            const panels = document.querySelectorAll(
              "ytd-engagement-panel-section-list-renderer",
            );
            for (const panel of panels) {
              if (
                panel.getAttribute("visibility") ===
                "ENGAGEMENT_PANEL_VISIBILITY_EXPANDED"
              ) {
                panel.querySelector('button[aria-label="Close"]')?.click();
              }
            }
          } catch (e) {
            // Never treat a failure to close as an error.
          }
        }

        // The page must actually be showing the requested video. After a
        // SPA navigation the URL changes first and the watch page's DOM
        // (description, transcript button) catches up a moment later.
        function pageShowsVideo() {
          if (!videoId) return true;
          if (new URLSearchParams(location.search).get("v") !== videoId) {
            return false;
          }
          const flexyId = document
            .querySelector("ytd-watch-flexy")
            ?.getAttribute("video-id");
          return !flexyId || flexyId === videoId;
        }

        try {
          const pageDeadline = Date.now() + 5000;
          while (!pageShowsVideo()) {
            if (Date.now() > pageDeadline) {
              return { ok: false, error: "VIDEO_MISMATCH" };
            }
            await sleep(200);
          }

          const stamp = window.__deepWatchTranscript;
          let lines = readSegments();
          const before = signature(lines);

          // Lines from a read we made for this exact video are safe to reuse.
          const trusted =
            before !== null &&
            videoId !== null &&
            stamp?.videoId === videoId &&
            stamp?.signature === before;

          let weOpenedPanel = false;

          if (!trusted) {
            // Whatever is in the panel may belong to another video. Make
            // YouTube load this one's: if the panel is open, close it first
            // so the button below really re-requests the transcript.
            if (before !== null && transcriptPanelIsOpen()) {
              closeOpenPanels();
              await sleep(300);
            }

            // Match the button structurally (inside this custom element),
            // not by its label text, since that text is localized. It can
            // render a moment after navigation, so wait for it briefly.
            let openButton = null;
            const buttonDeadline = Date.now() + 3000;
            while (!openButton) {
              openButton = document.querySelector(
                "ytd-video-description-transcript-section-renderer button",
              );
              if (openButton || Date.now() > buttonDeadline) break;
              await sleep(200);
            }
            if (!openButton) {
              return { ok: false, error: "NO_TRANSCRIPT" };
            }
            openButton.click();
            weOpenedPanel = true;

            // YouTube fetches the transcript asynchronously once the panel
            // opens; poll briefly rather than fixing a single delay. Old
            // lines still in the panel don't count: wait for them to change.
            const deadline = Date.now() + 8000;
            while (Date.now() < deadline) {
              await sleep(200);
              lines = readSegments();
              if (lines.length > 0 && signature(lines) !== before) break;
            }

            // Still identical to what was there before we asked. That is
            // fine if we can't tell where it came from (e.g. the user
            // opened the panel themselves) or it is provably this video's,
            // but never if we know it is another video's leftovers.
            if (
              lines.length > 0 &&
              signature(lines) === before &&
              stamp?.signature === before &&
              stamp?.videoId !== videoId
            ) {
              lines = [];
            }
          }

          // Best-effort: close the panel again if we're the ones who
          // opened it, so the viewer's page looks the way it did before.
          if (weOpenedPanel) closeOpenPanels();

          if (lines.length > 0 && videoId !== null) {
            window.__deepWatchTranscript = {
              videoId,
              signature: signature(lines),
            };
          }

          if (lines.length === 0) {
            return { ok: false, error: "EMPTY_TRANSCRIPT" };
          }
          return { ok: true, lines };
        } catch (e) {
          return { ok: false, error: e.message || "UNKNOWN_ERROR" };
        }
      },
    });
    return (
      results?.[0]?.result || { ok: false, error: "SCRIPT_INJECTION_FAILED" }
    );
  }

  /**
   * Converts the scraped {text, start} lines into our internal transcript
   * shape.
   *
   * YouTube's transcript panel exposes one timestamp per line and no
   * word-level offsets, unlike the raw caption file this used to parse.
   * Two fields are therefore approximated rather than exact:
   *   - `duration`: the gap to the next line (0 for the last line).
   *   - `segs`: a single entry covering the whole line. Every caller that
   *     reads `segs` (the Chat tab's word-clickable subtitle view) already
   *     falls back to line-level granularity when it has just one entry,
   *     so this only means clicking a line instead of a single word.
   */
  function buildTranscript(lines) {
    const transcript = [];
    let transcriptTextPlain = "";
    let transcriptTextTimestamped = "";

    for (let i = 0; i < lines.length; i++) {
      const { text, start } = lines[i];
      if (!text) continue;

      const next = lines[i + 1];
      const duration = next ? Math.max(0, next.start - start) : 0;
      const minutes = Math.floor(start / 60);
      const seconds = start % 60;
      const timestamp = `${minutes}:${String(seconds).padStart(2, "0")}`;

      transcript.push({
        text,
        start,
        duration,
        language: null,
        segs: [{ text, offsetMs: 0 }],
      });

      transcriptTextPlain += text + " ";
      transcriptTextTimestamped += `[${timestamp}] ${text}\n`;
    }

    return {
      transcript,
      transcriptTextPlain: transcriptTextPlain.trim(),
      transcriptTextTimestamped: transcriptTextTimestamped.trim(),
    };
  }

  /**
   * Fetches the transcript for the YouTube video open in `tabId`.
   *
   * @param {number} tabId - The YouTube tab to read the player from.
   * @param {string} [videoId] - The video the caller expects the tab to be
   *   showing. Guards against reading the previous video's transcript.
   * @returns {Object} success/failure result, see file header for shape.
   */
  async function fetchTranscript(tabId, videoId) {
    if (!tabId) {
      return {
        success: false,
        error: "NO_TAB",
        message: "Could not find the YouTube tab to read captions from.",
      };
    }

    let result;
    try {
      result = await fetchInPage(tabId, videoId);
    } catch (error) {
      return {
        success: false,
        error: "PLAYER_UNAVAILABLE",
        message:
          "Could not read the video page. Reload the YouTube tab and try again.",
      };
    }

    if (!result.ok) {
      if (result.error === "NO_TRANSCRIPT") {
        return {
          success: false,
          error: "NO_TRANSCRIPT",
          message: "No transcript is available for this video.",
        };
      }
      if (result.error === "VIDEO_MISMATCH") {
        return {
          success: false,
          error: "VIDEO_MISMATCH",
          message:
            "The YouTube tab moved to a different video before the transcript could be read.",
        };
      }
      if (result.error === "EMPTY_TRANSCRIPT") {
        return {
          success: false,
          error: "EMPTY_TRANSCRIPT",
          message:
            "YouTube's transcript panel returned no lines for this video.",
        };
      }
      return {
        success: false,
        error: "FETCH_FAILED",
        message: `Failed to read the transcript panel (${result.error}).`,
      };
    }

    const { transcript, transcriptTextPlain, transcriptTextTimestamped } =
      buildTranscript(result.lines);

    if (transcript.length === 0) {
      return {
        success: false,
        error: "EMPTY_TRANSCRIPT",
        message:
          "YouTube's transcript panel returned no lines for this video.",
      };
    }

    return {
      success: true,
      transcript,
      transcriptText: transcriptTextPlain,
      transcriptTextTimestamped: transcriptTextTimestamped,
      language: null,
    };
  }

  return { fetchTranscript, fetchInPage, buildTranscript };
})();

if (typeof module !== "undefined" && module.exports) {
  module.exports = DW_TRANSCRIPT_YOUTUBE;
}
